export enum CROPS {
    rice = 1.0,
    maize = 2.0,
    chickpea  = 3.0,
    kidneybeans = 4.0,
    pigeonpeas = 5.0,
    mothbeans = 6.0,
    mungbean = 7.0,
    blackgram = 8.0,
    lentil = 9.0,
    watermelon = 10.0,
    muskmelon = 11.0,
    cotton = 12.0,
    jute = 13.0,
}

export const CROPDURATIONS = {
    rice: 4,
    maize: 3,
    chickpea: 3,
    kidneybeans: 4,
    pigeonpeas: 5,
    mothbeans: 3,
    mungbean: 3,
    blackgram: 3,
    lentil: 3,
    watermelon: 3,
    muskmelon: 3,
    cotton: 6,
    jute: 4,
}